### ISSUE TITLE
type 'binary' is not supported - solved when removed this option :-)

### ISSUE THREAD

**Issue by daniel-rico** [LucaGiudice/Esearch3D#1]
Hi, the installation only happens when I remove the binary option.

Error: Failed to install 'Esearch3D' from GitHub:
  type 'binary' is not supported on this platform
> 
> 
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

**Comment by LucaGiudice** [comment]
Hi,
I understood the problem, the option is only available for Windows OS, I corrected the Readme and commented the parameter.

**Comment by daniel-rico** [comment]
Fab, thanks!
