### ISSUE TITLE
devtools not installing in R4.1

### ISSUE THREAD

**Issue by daniel-rico** [LucaGiudice/Esearch3D#2]
I am still fighting, but it does not seem stratightforward to install devtools in R4.1 - could we provide alternative way to install the package?

**Comment by LucaGiudice** [comment]
Hi,
following stackoverflow discussion, could you try to run the following operations?
install.packages("usethis")
install.packages("devtools")

cit. https://stackoverflow.com/questions/61522285/issue-in-installing-devtools-in-r-version-4-0

Consider the possibility to install and run the package with R 3.6.X
R 4.X is still quite new and many packages could be not updated to run properly with this version

**Comment by daniel-rico** [comment]
Hi Luca, thanks. It was a problem with the openssl, which was installed but not recognised. This finally did the trick: 

 sudo apt-get update && sudo apt-get install libssl-dev

**Comment by daniel-rico** [comment]
I will close this issue now.
